<!DOCTYPE html>
<html>
<head>
    <title>Detalle DE EMPLEADO</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <h1>Lista de Empleados</h1>
            <h3>Detalle</h3>

            <p><a href="/public">INICIO</a></p>

            <table class="table">
                <thead>
                <tr>
                    <th>name</th>
                    <th>email</th>
                    <th>phone</th>
                    <th>address</th>
                    <th>position</th>
                    <th>salary</th>
                    <th>skills</th>
                </tr>
                </thead>
                <tbody>
                <?php
                    if (!empty($colecciones)) { ?>
                            <tr>
                                <td><?php echo $colecciones['name'] ?></td>
                                <td><?php echo $colecciones['email'] ?></td>
                                <td><?php echo $colecciones['phone'] ?></td>
                                <td><?php echo $colecciones['address'] ?></td>
                                <td><?php echo $colecciones['position'] ?></td>
                                <td><?php echo $colecciones['salary'] ?></td>
                                <td>
                                    <?php
                                        foreach($colecciones['skills'] as $skill) {
                                            echo  $skill ["skill"] . '<br>';
                                        }
                                    ?>
                                </td>
                            </tr>
                        <?php
                    } ?>

                </tbody>
            </table>

        </div>
    </div>
</div>

</body>
</html>
}